name: Demo Workflow

on:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and Ruff
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
           python -m pip install --upgrade pip
           pip install ruff

      - name: Run Ruff Linter
        run: ruff .

  integration_tests:
    runs-on: ubuntu-latest
    services:

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
            docker build -t my-test-container-image -f app/Dockerfile .

      - name: Start Docker Compose
        run: |
            docker-compose up -d

      - name: Wait for service to be ready
        run: |
          echo "Waiting for the service to be ready..."
          sleep 30

      - name: Run automated tests
        run: |
          docker run --network="host" my-test-container-image pytest

  allure_report:
    runs-on: ubuntu-latest
    needs: integration_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Allure Report
        run: |
          curl -o allure.zip -L "https://github.com/allure-framework/allure2/releases/latest/download/allure-2.21.0.zip"
          unzip allure.zip -d allure
          sudo mv allure/* /usr/local/bin/

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
