name: Demo Workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      auth_service:
        image: mekidmetal/auth-service:latest  # Specify your authentication service image
        ports:
          - 8000
        options: >-
          --health-cmd "curl --fail http://127.0.0.1:8000/docs#/"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/test_grade_stats.py
