name: Demo Workflow

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    container:
      image: python:3.12
      
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/test_grade_stats.py
    
