name: Demo Workflow

on:
  push:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    env:
      RUN_LINTER: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # - name: Install Ruff
      #   run: |
      #     pip install ruff

      # - name: Run Ruff linter
      #   run: |
      #     ruff check tests/test_grade_stats.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run linters
      #   uses: github/super-linter@v4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for services to be ready
        run: |
          sleep 30

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests in Docker
        run: |
          docker run --network host 4e7024df2f20
      - name: Generate Allure report
        run: |
          allure serve ./allure-results

  deploy_report:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout report
        uses: actions/checkout@v2
        with:
          path: report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
