name: Demo Workflow

on:
  push

jobs:
#   lint:
#     name: Run linters
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.12'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pip install ruff

      # - name: Run Ruff linter
      #   run: ruff check .

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker Compose
        uses: docker/compose-action@v1
        with:
          run: up -d

      - name: Wait for services
        run: |
          # Better to use a proper health check
          docker-compose ps | grep -q "healthy"

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest  # Example test dependencies
          
      - name: Run tests
        run: |
          pytest --alluredir=./allure-results
          
      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: ./allure-results
          
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

  deploy_report:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: ./allure-results
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
