name: Demo Workflow

on:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and Ruff
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          
      # - name: Install Dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install ruff

      # - name: Run Ruff Linter
      #   run: ruff .

  integration_tests:
    runs-on: ubuntu-latest
    needs: linter
    services:
      my_service:
        image: mekidmetal/auth-service:latest
        ports:
          - 8000:8000
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Wait for service to be ready
        run: |
          echo "Waiting for the service to be ready..."
          sleep 30

      - name: Run automated tests
        run: |
          docker run --network="host" your-test-image:latest  # Замените на образ с вашими тестами

  allure_report:
    runs-on: ubuntu-latest
    needs: integration_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report
          mv ./allure-report ./path-to-your-report-directory  # Путь для GitHub Pages

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path-to-your-report-directory
